export const Images = {
  bg_splash: require('../assets/images/bg_splash-0.jpg'),
  bg_setting: require('../assets/images/bg_setting.png'),
  bg_opentab: require('../assets/images/bg_opentab.png'),
  bg_opentab_detail_top: require('../assets/images/bg_opentab_detail_top.png'),
  bg_opentab_detail_bottom: require('../assets/images/bg_opentab_detail_bottom.png'),
  bg_social_bottom: require('../assets/images/bg_social_bottom.png'),
  bg_setting_btn: require('../assets/images/bg_setting_btn.png'),
  bg_logo0: require('../assets/images/logo0.png'),
  bg_logo1: require('../assets/images/logo1.png'),
  bg_logo2: require('../assets/images/logo2.png'),

  logo: require('../assets/images/40.png'),
  logo_black: require('../assets/images/logo_black.png'),
  logo_tag: require('../assets/images/logo_tag.png'),
  logo_support: require('../assets/images/logo_support.png'),
  logo_opentab: require('../assets/images/logo_opentab.png'),
  logo_wallet: require('../assets/images/logo_wallet.png'),
  logo_good: require('../assets/images/modal_logo3.jpg'),
  logo_empty_offer: require('../assets/images/empty_offer.png'),
  logo_stripe: require('../assets/images/stripe_white.jpg'),
  not_in_your_area: require('../assets/images/not-in-your-area.png'),
  promo: require('../assets/images/promo.png'),
  withdraw_error: require('../assets/images/withdraw_error.png'),

  avatar_female_1: require('../assets/images/avatar-female-1.png'),
  avatar_female_2: require('../assets/images/avatar-female-2.png'),
  avatar_male_1: require('../assets/images/avatar-male-1.png'),
  avatar_male_2: require('../assets/images/avatar-male-2.png'),

  btn_opentab: require('../assets/images/btn_opentab.png'),
  btn_social_send: require('../assets/images/btn_social_send.png'),
  btn_wallet_price: require('../assets/images/btn_wallet_price.png'),
  btn_split: require('../assets/images/btn_split.png'),

  ic_wallet_sent: require('../assets/images/ic_wallet_sent.png'),
  ic_qrscan_mark: require('../assets/images/ic_qrscan_mark.png'),
  ic_qrscan_areatl: require('../assets/images/ic_qrscan_areatl.png'),
  ic_qrscan_areatr: require('../assets/images/ic_qrscan_areatr.png'),
  ic_qrscan_areabl: require('../assets/images/ic_qrscan_areabl.png'),
  ic_qrscan_areabr: require('../assets/images/ic_qrscan_areabr.png'),
  ic_no_user: require('../assets/images/ic_no_user.png'),
  ic_dummy_thumb: require('../assets/images/ic_dummy_thumb.jpg'),
  ic_flute: require('../assets/images/ic_flute.png'),

  ic_slider_tick: require('../assets/images/ic_slider_tick.png'),

  ic_triangle: require('../assets/images/Triangle.png'),
  ic_return: require('../assets/images/ic_return.png'),
  ic_check: require('../assets/images/ic_check.png'),
  ic_check_gold: require('../assets/images/ic_check_gold.png'),
  ic_uncheck: require('../assets/images/ic_uncheck.png'),
  ic_placeholder: require('../assets/images/item_placeholder.png'),
  ic_apple_pay: require('../assets/images/ic_apple_pay.png'),
  ic_receipt: require('../assets/images/ic_receipt_blank.png'),
  ic_bottle: require('../assets/images/product2.png'),
  ic_blur_back: require('../assets/images/blur-back.png'),

  rebate_issue: require('../assets/images/rebate-issue.png'),
  duplicate_issue: require('../assets/images/duplicate-issue.png')
};
